version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/openjdk:17.0  # Java 17, update if you use a different version
    steps:
      - checkout

      # Standard Maven lifecycle commands
      - run:
          name: Clean Project
          command: mvn clean

      - run:
          name: Compile Project
          command: mvn compile

      - run:
          name: Run Tests
          command: mvn test

      - run:
          name: Package App
          command: mvn package

      # Create and send the JAR to EC2
      - run:
          name: Deploy to EC2
          command: |
            mkdir -p output
            cp target/*.jar output/app.jar
            tar -czf output/deploy.tar.gz -C output app.jar

            scp -o StrictHostKeyChecking=no output/deploy.tar.gz ubuntu@35.183.24.169:~/app

            ssh -o StrictHostKeyChecking=no ubuntu@35.183.24.169 "
              set -e
              sudo apt update &&
              sudo apt install -y openjdk-17-jdk &&
              mkdir -p ~/app &&
              cd ~/app &&
              tar -xzf deploy.tar.gz &&
              rm deploy.tar.gz &&

              # Kill any old app running on port 8080
              PID=\$(lsof -t -i:8080 || true) &&
              if [ -n \"\$PID\" ]; then kill -9 \$PID; fi &&

              # Run new JAR in background
              nohup java -jar app.jar > app.log 2>&1 &
            "

workflows:
  deploy_flow:
    jobs:
      - deploy
