- name: CI/CD pipeline for Java Maven Project
  hosts: webservers
  become: yes

  vars:
    ansible_user: ubuntu
    app_dir: /home/{{ ansible_user }}/gameboard
    repo_url: https://github.com/student-shraddha/gameboard.git

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - openjdk-17-jdk
          - maven
        state: present

    - name: Ensure JAVA_HOME is set in /etc/environment
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
        create: yes
        state: present

    - name: Remove existing app directory
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone Java Maven repo
      become_user: "{{ ansible_user }}"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: master
        force: yes

    - name: Build project using Maven
      become_user: "{{ ansible_user }}"
      shell: mvn clean package -DskipTests
      args:
        chdir: "{{ app_dir }}"

    - name: List contents of target directory (debugging)
      become_user: "{{ ansible_user }}"
      shell: ls -l target
      args:
        chdir: "{{ app_dir }}"
      register: target_contents
      ignore_errors: yes

    - name: Show target directory listing
      debug:
        var: target_contents.stdout_lines

    - name: Find built JAR file
      find:
        paths: "{{ app_dir }}/target"
        patterns: "*.jar"
        recurse: no
      register: jar_files

    - name: Copy built JAR to deploy location
      when: jar_files.files | length > 0
      copy:
        src: "{{ jar_files.files[0].path }}"
        dest: "/home/{{ ansible_user }}/app.jar"
        remote_src: yes

    - name: Fail if JAR file was not found
      when: jar_files.files | length == 0
      fail:
        msg: "No JAR file found in {{ app_dir }}/target. Maven build may have failed or project may not produce a JAR."

    - name: Stop existing Java app if running
      shell: |
        pkill -f 'java -jar' || true

    - name: Start Java app
      shell: |
        nohup java -jar /home/{{ ansible_user }}/app.jar > /home/{{ ansible_user }}/app.log 2>&1 &
